### ISSUE TITLE
Fatal error when ACF is not active

### ISSUE THREAD

**Issue by lopwalj** [wpsmith/Taxonomy#1]
Seems like error is coming from [line #246](https://github.com/wpsmith/Taxonomy/blob/master/src/Taxonomy.php#L246):
`$this->add_action( 'plugins_loaded', array( $this, 'initialize_fields' ) );`

I'm not sure why you are running this action as I don't see any custom field assigned to the taxonomy.

I think this library should run without a premium dependency and principally if you are not needing a custom field. Thoughts?

**Comment by wpsmith** [comment]
Fixed with #13c06c1
